server:
  port: 8084

spring:
  application:
    name: addevent-service

  datasource:
    url: jdbc:postgresql://localhost:5432/alleventsdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/