
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Put CORS configuration before routes
      globalcors:
        add-to-simple-url-handler-mapping: true  # Add this line
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "Authorization"
              - "Content-Type"
              - "Accept"
            allowCredentials: true
            maxAge: 3600
      routes:
        # Public routes first
        - id: auth-public
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin  # Add this line

        - id: events-public
          uri: lb://event-service
          predicates:
            - Path=/api/events/public/**


        - id: clubs-public
          uri: lb://CLUBS
          predicates:
            - Path=/api/clubs/public/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin

        # Protected routes after

        - id: event-serivce
          uri: lb://event-service
          predicates:
                   - Path=/api/events/**
          filters:
            - AuthenticationFilter
            - DedupeResponseHeader=Access-Control-Allow-Origin

        - id: notification-serivce
          uri: lb://notification-service
          predicates:
                   - Path=/api/notifications/**
          filters:
            - AuthenticationFilter
            - DedupeResponseHeader=Access-Control-Allow-Origin 

        - id: profile-serivce
          uri: lb://profile-service
          predicates:
                   - Path=/api/profile/**
          filters:
            - AuthenticationFilter
            - DedupeResponseHeader=Access-Control-Allow-Origin               


eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET}

       
