server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: view-serivce
          uri: lb://view-serivce
          predicates:
            - Path=/api/events/public/**

        - id: view-serivce-protected
          uri: lb://view-serivce
          predicates:
            - Path=/api/events/**
          filters:
            - name: AuthenticationFilter
              args: {}

        - id: add-serivce
          uri: lb://add-serivce
          predicates:
            - Path=/api/events/public/**
          filters:
            - name: AuthenticationFilter
              args: {}

        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/profile/**
          filters:
            - name: AuthenticationFilter
              args: {}

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


jwt:
  secret: H8hS3jF5kL9qW7nE4zR6tU5yB2vM8pC1
